// Combines the active mods, in load order, on top of the game's original files.
//
// For every game file some mod touches, a list of steps is built in order:
//   override  the mod ships the whole file
//   patch     the mod ships operations (its own, or generated by comparing its file to the original)
// and they run on top of the original. A whole SGO/DSGO file that can be compared against the
// original is turned into a patch automatically, so old-style mods combine too.

const fs = require('fs')
const codec = require('./codec')
const { apply } = require('./patch')
const { diff } = require('./diff')
const { analyze } = require('./conflicts')
const { fileKey, indexDir } = require('./mods')
const { gameTopDirs, isUserData } = require('./vanilla')

function collectSteps(mods, vanilla, notes) {
  const steps = new Map() // key -> { rel, steps: [] }
  const add = (rel, step) => {
    const key = fileKey(rel)
    const known = vanilla.relOf ? vanilla.relOf(key) : vanilla.get(key)?.rel
    if (!steps.has(key)) steps.set(key, { rel: known || rel.replace(/\\/g, '/'), steps: [] })
    steps.get(key).steps.push(step)
  }

  for (const mod of mods) {
    for (const file of mod.files) {
      const buffer = fs.readFileSync(file.abs)
      const base = codec.isPatchable(buffer) ? vanilla.get(fileKey(file.rel)) : undefined
      if (base) {
        const { ops, warnings } = diff(codec.readDoc(base.abs), codec.decode(buffer))
        if (warnings.length === 0) {
          add(file.rel, { type: 'patch', mod: mod.id, ops, auto: true })
          continue
        }
        notes.push(`${mod.id}: ${file.rel} could not be turned into a patch (${warnings[0]}); using the whole file`)
      } else if (codec.isPatchable(buffer)) {
        notes.push(`${mod.id}: ${file.rel} is not among the originals; using the whole file, it won't combine`)
      }
      add(file.rel, { type: 'override', mod: mod.id, buffer })
    }
    for (const [rel, ops] of Object.entries(mod.patches)) {
      add(rel, { type: 'patch', mod: mod.id, ops, auto: false })
    }
  }
  return steps
}

function buildFile(key, entry, vanilla, events, errors) {
  let doc = null
  let raw = null
  let changed = false // patched files are recompiled; otherwise the file is copied as is

  for (const step of entry.steps) {
    if (step.type === 'override') {
      events.push({ mod: step.mod, file: entry.rel, path: null, kind: 'override' })
      raw = step.buffer
      doc = codec.isPatchable(raw) ? codec.decode(raw) : null
      changed = false
      continue
    }

    if (!doc) {
      if (raw) {
        errors.push({ mod: step.mod, file: entry.rel, message: 'the file is not SGO/DSGO and cannot be patched' })
        return null
      }
      const base = vanilla.get(key)
      if (!base) {
        errors.push({
          mod: step.mod,
          file: entry.rel,
          message: 'the original file is missing (it is not in the originals folder nor in Root.cpk)',
        })
        return null
      }
      doc = codec.readDoc(base.abs)
    }

    step.ops.forEach((op, i) => {
      try {
        for (const e of apply(doc, op)) events.push({ mod: step.mod, file: entry.rel, ...e })
        changed = true
      } catch (e) {
        const where = step.auto ? 'generated patch' : `operation #${i + 1}`
        errors.push({ mod: step.mod, file: entry.rel, message: `${where} (${op.op} ${op.path}): ${e.message}` })
      }
    })
  }

  return changed ? codec.encode(doc) : raw
}

// mods: already loaded mods, in load order (the last one wins).
// vanilla: something with get(fileKey) -> { rel, abs } (see vanilla.js); or vanillaDir to use
// only the files in that folder.
function build(mods, { vanilla, vanillaDir }) {
  vanilla = vanilla || (vanillaDir ? indexDir(vanillaDir) : new Map())
  const notes = []
  const events = []
  const errors = []
  const outputs = new Map()

  const steps = collectSteps(mods, vanilla, notes)
  let dirs = null // read only if there are outputs, since it may open the CPKs
  for (const [key, entry] of steps) {
    const buffer = buildFile(key, entry, vanilla, events, errors)
    if (buffer) {
      dirs = dirs || gameTopDirs(vanilla)
      outputs.set(key, {
        rel: entry.rel,
        buffer,
        mods: [...new Set(entry.steps.map(s => s.mod))],
        ...(isUserData(entry.rel, dirs) && { userData: true }),
      })
    }
  }

  return { outputs, conflicts: analyze(events), notes, errors }
}

module.exports = { build }
